
Namespace theoraplayer

'***** ogg *****
'
#Import "native/ogg/src/bitwise.c"
#Import "native/ogg/src/framing.c"

'***** vorbis *****
'
#Import "native/vorbis/lib/analysis.c"
'#Import "native/vorbis/lib/barkmel.c"
#Import "native/vorbis/lib/bitrate.c"
#Import "native/vorbis/lib/block.c"
#Import "native/vorbis/lib/codebook.c"
#Import "native/vorbis/lib/envelope.c"
#Import "native/vorbis/lib/floor0.c"
#Import "native/vorbis/lib/floor1.c"
#Import "native/vorbis/lib/info.c"
#Import "native/vorbis/lib/lookup.c"
#Import "native/vorbis/lib/lpc.c"
#Import "native/vorbis/lib/lsp.c"
#Import "native/vorbis/lib/mapping0.c"
#Import "native/vorbis/lib/mdct.c"
#Import "native/vorbis/lib/psy.c"
'#Import "native/vorbis/lib/psytune.c"
#Import "native/vorbis/lib/registry.c"
#Import "native/vorbis/lib/res0.c"
#Import "native/vorbis/lib/sharedbook.c"
#Import "native/vorbis/lib/smallft.c"
#Import "native/vorbis/lib/synthesis.c"
'#Import "native/vorbis/lib/tone.c"
#Import "native/vorbis/lib/vorbisenc.c"
#Import "native/vorbis/lib/vorbisfile.c"
#Import "native/vorbis/lib/window.c"

'***** theora *****
'
'#Import "native/theora/lib/analyze.c"
#Import "native/theora/lib/apiwrapper.c"
#Import "native/theora/lib/bitpack.c"
#Import "native/theora/lib/collect.c"
#Import "native/theora/lib/decapiwrapper.c"
#Import "native/theora/lib/decinfo.c"
#Import "native/theora/lib/decode.c"
#Import "native/theora/lib/dequant.c"
'#Import "native/theora/lib/encapiwrapper.c"
'#Import "native/theora/lib/encfrag.c"
'#Import "native/theora/lib/encinfo.c"
'#Import "native/theora/lib/encode.c"
#Import "native/theora/lib/encoder_disabled.c"
#Import "native/theora/lib/enquant.c"
#Import "native/theora/lib/fdct.c"
#Import "native/theora/lib/fragment.c"
#Import "native/theora/lib/huffdec.c"
#Import "native/theora/lib/huffenc.c"
#Import "native/theora/lib/idct.c"
#Import "native/theora/lib/info.c"
#Import "native/theora/lib/internal.c"
#Import "native/theora/lib/mathops.c"
'#Import "native/theora/lib/mcenc.c"
#Import "native/theora/lib/quant.c"
#Import "native/theora/lib/rate.c"
#Import "native/theora/lib/state.c"
#Import "native/theora/lib/tokenize.c"

'#Import "native/theora/lib/x86/mmxencfrag.c
'#Import "native/theora/lib/x86/mmxfdct.c"
'#Import "native/theora/lib/x86/mmxfrag.c"
'#Import "native/theora/lib/x86/mmxidct.c"
'#Import "native/theora/lib/x86/mmxstate.c"
'#Import "native/theora/lib/x86/sse2encfrag.c"
'#Import "native/theora/lib/x86/sse2fdct.c"
'#Import "native/theora/lib/x86/sse2idct.c"
'#Import "native/theora/lib/x86/x86cpu.c"
'#Import "native/theora/lib/x86/x86enc.c"
'#Import "native/theora/lib/x86/x86enquant.c"
'#Import "native/theora/lib/x86/x86state.c"

'***** theoraplayer *****
'
#Import "native/theoraplayer/src/AudioInterface.cpp"
#Import "native/theoraplayer/src/AudioInterfaceFactory.cpp"
#Import "native/theoraplayer/src/AudioPacketQueue.cpp"
#Import "native/theoraplayer/src/DataSource.cpp"
#Import "native/theoraplayer/src/Exception.cpp"
#Import "native/theoraplayer/src/FileDataSource.cpp"
#Import "native/theoraplayer/src/FrameQueue.cpp"
#Import "native/theoraplayer/src/Manager.cpp"
#Import "native/theoraplayer/src/MemoryDataSource.cpp"
#Import "native/theoraplayer/src/Mutex.cpp"
#Import "native/theoraplayer/src/theoraplayer.cpp"
#Import "native/theoraplayer/src/Thread.cpp"
#Import "native/theoraplayer/src/Timer.cpp"
#Import "native/theoraplayer/src/Utility.cpp"
#Import "native/theoraplayer/src/VideoClip.cpp"
#Import "native/theoraplayer/src/VideoFrame.cpp"
#Import "native/theoraplayer/src/WorkerThread.cpp"

#Import "native/theoraplayer/src/YUV/yuv_util.c"

#Import "native/theoraplayer/src/formats/Theora/VideoClip_Theora.cpp"

#Import "native/theoraplayer/src/YUV/C/yuv420_grey_c.c"
#Import "native/theoraplayer/src/YUV/C/yuv420_rgb_c.c"
#Import "native/theoraplayer/src/YUV/C/yuv420_yuv_c.c"

#Import "native/theoraplayer/src/YUV/libyuv/src/compare.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/compare_common.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/compare_gcc.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/compare_neon.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/compare_neon64.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/compare_posix.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/compare_win.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert_argb.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert_from.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert_from_argb.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert_jpeg.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert_to_argb.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/convert_to_i420.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/cpu_id.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/mjpeg_decoder.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/mjpeg_validate.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/planar_functions.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/rotate.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/rotate_argb.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/rotate_mips.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/rotate_neon.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/rotate_neon64.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_any.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_common.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_gcc.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_mips.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_neon.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_neon64.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_posix.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/row_win.cc"
'#Import "native/theoraplayer/src/YUV/libyuv/src/row_x86.asm"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_any.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_argb.cc"
'#Import "native/theoraplayer/src/YUV/libyuv/src/scale_argb_neon.cc"	'problem on ios arm64...
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_common.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_gcc.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_mips.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_neon.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_neon64.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_posix.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/scale_win.cc"
#Import "native/theoraplayer/src/YUV/libyuv/src/video_common.cc"
'#Import "native/theoraplayer/src/YUV/libyuv/src/x86inc.asm"

#Import "native/theoraplayer/src/YUV/libyuv/yuv_libyuv.c"
